version: '3'
services:
  app:
    build: '.'
    volumes:
      - './.cache:/app/.cache'
      - './config.yaml:/app/config.yaml'
    environment:
      - FETCH_STATUS_COUNT
      - STATE_SIZE
      - MIN_WORDS_COUNT
      - DRY_RUN
